# Use the mold linker
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    "target-cpu=native",
    "-Z",
    "share-generics=y",
    "-C",
    "link-arg=-fuse-ld=/usr/bin/mold",
]

[registries.crates-io]
protocol = "sparse"
